training_dir: "outputs/2025-11-28/15-51-02"
checkpoint: "checkpoints/final_policy_epoch_200/model"
output_dir: ${hydra:runtime.output_dir}
start_idx: -1
end_idx: -1
eval_count: 10
eval_view: "fixed_cam"
device: "cpu"
