RRT:
  verbose: 3
  max_nodes: 2500
  min_cost: 0.05
  horizon: 1
  max_configs: 100
  stepsize: 0.05
  path_diff_thresh: 0.05
  target_min_dist: 10.
  target_prob: .2
  disable_node_max_strikes: 1
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 1
  end_idx: -1
  bidirectional: false
  cost_max_method: false
  sample_count: 500
  sampling_strategy: rs
  n_best_actions: 16  # Only for random sampling strategy
  cem_steps: 10  # Only for CEM
  regularization_weight: .01
  output_dir: ${hydra:runtime.output_dir}
  q_mask:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 2
  - .25
  - .25
  - .25
  - .25
  knnK: 16
  sim:
    tau_sim: 0.005
    tau_action: 0.25
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/twoFingersCube.xml
    camera: fixed_cam
configs_path: configs/stable/twoFingersCube.h5