hydra:
  sweeper:
    params:
      RRT.start_idx: 1,2,3,4,5,6,7,8,9,10

RRT:
  verbose: 1
  max_nodes_per_tree: 2500
  min_cost: 0.001
  horizon: 1
  max_configs: 100
  stepsize: 0.08
  path_diff_thresh: 0.05
  target_min_dist: 1000.0
  target_prob: 0.2
  disable_node_max_strikes: 1
  sample_uniform_prob: 0.0
  warm_start: false
  threading: true
  start_idx: -1
  end_idx: -1
  bidirectional: false
  cost_method: se
  sample_count: 100
  sampling_strategy: rs
  n_best_actions: 16
  cem_steps: 10
  regularization_weight: 0.0
  output_dir: ${hydra:runtime.output_dir}
  q_mask:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  knnK: 16
  sim:
    tau_sim: 0.005
    tau_action: 0.4
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/fingerRamp.xml
    camera: fixed_cam
configs_path: configs/stable/fingerRamp_onRamp.h5