hydra:
  sweeper:
    params:
      RRT.start_idx: 1,2,3,4,5,6,7,8,9,10
      knnK: 1

RRT:
  verbose: 3
  max_nodes: 2500
  min_cost: 0.001
  horizon: 1
  max_configs: -1
  stepsize: 0.08
  path_diff_thresh: 0.05
  target_min_dist: 1000.
  target_prob: .0
  disable_node_max_strikes: 1
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 1
  end_idx: -1
  bidirectional: false
  cost_method: se
  sample_count: 100
  sampling_strategy: rs
  n_best_actions: 16  # Only for random sampling strategy
  cem_steps: 10  # Only for CEM
  regularization_weight: .0
  output_dir: ${hydra:runtime.output_dir}
  q_mask:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  knnK: 1
  sim:
    tau_sim: 0.005
    tau_action: 0.4
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/fingerRamp.xml
    camera: fixed_cam
configs_path: configs/stable/fingerRamp_onRamp.h5
