rl_method: "SAC"
verbose: 1
total_timesteps: 2e7
output_dir: ${hydra:runtime.output_dir}
device: "cpu"
net_arch: [256, 256]
save_freq: 25e4
env:
  time_scaling: 1.0
  stepsize: 0.04
  max_steps: 125
  actions_noise_sigma: 0.001
  use_vel: true
  guiding: true
  guiding_prob: 1.
  start_config_idx: -1
  target_config_idx: -1
  goal_conditioning: true
  use_vision: false
  camera_filter: "balls_mask"
  verbose: 1
  sim:
    tau_sim: 0.001
    tau_action: 0.1
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    mujoco_xml: "configs/mujoco_/fingerRamp.xml"
    camera: wrist_cam
  trajectory_data_path: "data/fingerRamp_full"  # TODO: either make this optionam or remove stable_configs_path and mujoco_xml or idk.
  stable_configs_path: "configs/stable/fingerRamp_onRamp.h5"
