data_dir: data/fingerRamp_exp
batch_size: 256
epochs: 200
data_tau_action: 0.1
device: cuda
trainer:
  lr: 0.0003
  weight_decay: 0.01
  warmup_fraction: 0.03
  checkpoint_every: 100
  sim_eval_count: 4
  output_dir: ${hydra:runtime.output_dir}
  use_ema: true
  ema:
    update_after_step: 0
    inv_gamma: 1.0
    power: 0.75
    min_value: 0.0
    max_value: 0.9999
policy:
  horizon: 8
  history: 4
  effective_horizon: 1
  denoising_steps: 64
  model_type: transformer
  network:
    n_layer: 8
    n_head: 4
    emb_dim: 256
    p_drop_emb: 0.1
    p_drop_attn: 0.1
    causal_attn: true
    obs_as_cond: true
    n_cond_layers: 0
    verbose: 1
env:
  time_scaling: 1.0
  stepsize: -1
  max_steps: 32
  actions_noise_sigma: 0.001
  use_vel: false
  guiding: false
  guiding_prob: 1.0
  start_config_idx: -1
  target_config_idx: -1
  goal_conditioning: true
  use_vision: false
  camera_filter: balls_mask
  render_w: 480
  render_h: 320
  verbose: 1
  sim:
    tau_sim: 0.005
    tau_action: 0.5
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    mujoco_xml: configs/mujoco_/fingerRamp.xml
    camera: fixed_cam
  trajectory_data_path: data/fingerRamp_exp
  stable_configs_path: configs/stable/fingerRamp_onRamp.h5
