RRT:
  verbose: 3
  max_nodes: 500000
  min_cost: 0.06
  max_configs: -1
  stepsize: [
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .05,  # waist
    .75, .75, .75,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
    .05, .05, .05,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
  ]
  path_diff_thresh: 0.05
  target_min_dist: 100.
  target_prob: .15
  sample_uniform: false
  start_idx: 8
  end_idx: -1
  cost_max_method: false
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    2., 2., 2., .25, .25, .25, .25,
    .5, .5, .5,  # hip
    .4, .125, .125,  # knee, ankle, ankle
    .5, .5, .5,  # hip
    .25, .125, .125,  # knee, ankle, ankle
    .7, .7, .7,  # waist
    .4, .4, .4,  # shoulder
    .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
    .4, .4, .4,  # shoulder
    .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
  ]
  knnK: 32
  sim:
    tau_sim: 0.01
    tau_action: 0.1
    interpolate_actions: false
    joints_are_same_as_ctrl: false
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/g1/scene.xml
    camera: fixed_cam
configs_path: configs/stable/g1.h5

# hydra:
#   sweeper:
#     params:
#       RRT.horizon: 1, 2, 4
#       RRT.max_configs: 128, -1
#       RRT.sim.use_spline_ref: true, false
#       RRT.regularization_weight: .0, .1
#       RRT.sampling_strategy: cem, rs
    