RRT:
  verbose: 1
  max_nodes: 5000
  min_cost: 0.1
  horizon: 20
  max_configs: 256
  # stepsize: [
  #   1.0821, 0.69814, 1.10304, 0.5934134, 0.279254, 0.10472, 1.0821,
  #   0.69814, 1.10304, 0.5934134, 0.279254, 0.10472, 1.0472, 0.208,
  #   0.208, 1.15192, 0.76794, 1.0472, 0.62832, 0.788888, 0.645772,
  #   0.645772, 1.15192, 0.76794, 1.0472, 0.62832, 0.788888, 0.645772, 0.645772
  # ]  # 0.2
  # stepsize: [
  #   0.54105, 0.34907, 0.55152, 0.2967067, 0.139627, 0.05236,
  #   0.54105, 0.34907, 0.55152, 0.2967067, 0.139627, 0.05236,
  #   0.5236, 0.104, 0.104, 0.57596, 0.38397,
  #   0.5236, 0.31416, 0.394444, 0.322886, 0.322886,
  #   0.57596, 0.38397, 0.5236, 0.31416, 0.394444, 0.322886, 0.322886
  # ]  # 0.1
  # stepsize: [
  #   0.270525, 0.174535, 0.27576, 0.14835335000000002, 0.0698135, 0.02618,
  #   0.270525, 0.174535, 0.27576, 0.14835335000000002, 0.0698135, 0.02618,
  #   0.2618, 0.052000000000000005, 0.052000000000000005, 0.28798, 0.19198500000000002,
  #   0.2618, 0.15708, 0.197222, 0.161443, 0.161443, 0.28798, 0.19198500000000002,
  #   0.2618, 0.15708, 0.197222, 0.161443, 0.161443
  # ]  # 0.05
  # stepsize: [
  #   0.054105, 0.034907, 0.055152, 0.029670670000000003, 0.0139627,
  #   0.005235999999999999, 0.054105, 0.034907, 0.055152, 0.029670670000000003, 0.0139627,
  #   0.005235999999999999, 0.05236, 0.010400000000000001, 0.010400000000000001, 0.057596,
  #   0.038397, 0.05236, 0.03141599999999999, 0.039444400000000004, 0.0322886, 0.0322886, 0.057596,
  #   0.038397, 0.05236, 0.03141599999999999, 0.039444400000000004, 0.0322886, 0.0322886
  # ]  # 0.01
  # stepsize: [
  #   0.1352625, 0.0872675, 0.13788, 0.07417667500000001, 0.03490675, 0.01309, 0.1352625, 0.0872675, 0.13788, 0.07417667500000001, 0.03490675, 0.01309, 0.1309, 0.026000000000000002, 0.026000000000000002, 0.14399, 0.09599250000000001, 0.1309, 0.07854, 0.098611, 0.0807215, 0.0807215, 0.14399, 0.09599250000000001, 0.1309, 0.07854, 0.098611, 0.0807215, 0.0807215
  # ]  # 0.025
  #   Range
  #   5.4105   3.4907   5.5152
  #   2.967067 1.39627  0.5236
  #   5.4105   3.4907   5.5152
  #   2.967067 1.39627  0.5236
  #   5.236    1.04     1.04
  #   5.7596   3.8397   5.236    3.1416
  #   3.94444  3.22886  3.22886
  #   5.7596   3.8397.  5.236
  #   3.1416   3.94444  3.22886  3.22886
  stepsize: [
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .05,  # waist
    .75, .75, .75,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
    .05, .05, .05,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
  ]
  path_diff_thresh: 0.05
  k_nearest_targets: -1
  target_prob: .1
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 1
  end_idx: 8
  bidirectional: false
  cost_max_method: true
  n_best_actions: 1  # Only for random sampling strategy
  sample_count: 1000
  sampling_strategy: rs
  cem_steps: 3
  regularization_weight: .1
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    0., 0., 2.5, 1., 1., 1., 1.,
    1., 1., 1.,  # hip
    .75, .25, .25,  # knee, ankle, ankle
    1., 1., 1.,  # hip
    .5, .25, .25,  # knee, ankle, ankle
    1.25, 1.25, 1.25,  # waist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
  ]
  knnK: 128
  sim:
    tau_sim: 0.005
    tau_action: 0.05
    interpolate_actions: false
    joints_are_same_as_ctrl: false
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/unitree_g1/g1_single.xml
    camera: fixed_cam
configs_path: configs/stable/g1.h5
