RRT:
  max_nodes: 1000
  min_cost: 0.6
  stepsize: 0.1
  verbose: 1
  path_diff_thresh: 0.05
  target_prob: 0.2
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 8
  end_idx: 39
  bidirectional: false
  cost_max_method: false
  n_best_actions: 32
  sample_count: 1000
  sampling_strategy: rs
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    .0, .0, 4., 2.5, 2.5, 2.5, 2.5, 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
    1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.
  ]
  knnK: 32
  sim:
    tau_sim: 0.005
    tau_action: 0.25
    interpolate_actions: false
    joints_are_same_as_ctrl: false
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/unitree_g1/g1_single.xml
    camera: fixed_cam
configs_path: configs/stable/g1.h5
