# RRT:
#   verbose: 3
#   max_nodes: 10000
#   min_cost: 0.06
#   max_configs: 128
#   stepsize: [
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .05,  # waist
#     .75, .75, .75,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#     .05, .05, .05,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#   ]
#   path_diff_thresh: 0.05
#   target_min_dist: 100.
#   target_prob: .15
#   sample_uniform: false
#   start_idx: 8
#   end_idx: -1
#   cost_max_method: false
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask: [
#     2., 2., 2., .25, .25, .25, .25,
#     .5, .5, .5,  # hip
#     .4, .125, .125,  # knee, ankle, ankle
#     .5, .5, .5,  # hip
#     .25, .125, .125,  # knee, ankle, ankle
#     .7, .7, .7,  # waist
#     .4, .4, .4,  # shoulder
#     .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
#     .4, .4, .4,  # shoulder
#     .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
#   ]
#   knnK: 32
#   sim:
#     tau_sim: 0.001
#     tau_action: 0.1
#     interpolate_actions: false
#     joints_are_same_as_ctrl: false
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/g1/scene.xml
#     camera: fixed_cam
# configs_path: configs/stable/g1.h5

# # hydra:
# #   sweeper:
# #     params:
# #       RRT.horizon: 1, 2, 4
# #       RRT.max_configs: 128, -1
# #       RRT.sim.use_spline_ref: true, false
# #       RRT.regularization_weight: .0, .1
# #       RRT.sampling_strategy: cem, rs


RRT:
  verbose: 3
  max_nodes: 6500
  min_cost: 0.05
  horizon: 1
  max_configs: -1
  stepsize: [
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .05,  # waist
    .75, .75, .75,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
    .05, .05, .05,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
  ]
  path_diff_thresh: 0.05
  target_min_dist: 3.
  target_prob: .1
  disable_node_max_strikes: 5
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 8
  end_idx: -1
  bidirectional: false
  cost_max_method: true
  sample_count: 2500
  sampling_strategy: rs
  n_best_actions: 1000  # Only for random sampling strategy
  cem_steps: 5  # Only for CEM
  regularization_weight: .0
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    4., 4., 4., .25, .25, .25, .25,
    1., 1., 1.,  # hip
    .75, .25, .25,  # knee, ankle, ankle
    1., 1., 1.,  # hip
    .5, .25, .25,  # knee, ankle, ankle
    1.25, 1.25, 1.25,  # waist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
    # .01, .01, .01,  # hip
    # .01, .01, .01,  # knee, ankle, ankle
    # .01, .01, .01,  # hip
    # .01, .01, .01,  # knee, ankle, ankle
    # .01, .01, .01,  # waist
    # .01, .01, .01,  # shoulder
    # .01, .01, .01, .01,  # elbow, wrist, wrist, wrist
    # .01, .01, .01,  # shoulder
    # .01, .01, .01, .01,  # elbow, wrist, wrist, wrist
  ]
  knnK: 16
  sim:
    tau_sim: 0.005
    tau_action: 0.2
    interpolate_actions: false
    joints_are_same_as_ctrl: false
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/unitree_g1/g1_single.xml
    camera: fixed_cam
configs_path: configs/stable/g1.h5

# RRT:
#   verbose: 3
#   # max_nodes: 535000
#   max_nodes: 2500
#   min_cost: 0.4
#   horizon: 1
#   max_configs: -1
#   stepsize:
#   - 0.15
#   - 0.15
#   - 0.2
#   - 0.25
#   - 0.35
#   - 0.3
#   - 0.5
#   - 125.0
#   - 0.15
#   - 0.15
#   - 0.2
#   - 0.25
#   - 0.35
#   - 0.3
#   - 0.5
#   - 125.0
#   path_diff_thresh: 0.05
#   target_min_dist: 10.
#   target_prob: .1
#   disable_node_max_strikes: 5
#   sample_uniform: false
#   warm_start: false
#   threading: true  # Depending on the hardware this may lead to faster computations.
#   start_idx: 1
#   end_idx: -1
#   bidirectional: false
#   cost_max_method: true
#   sample_count: 2500
#   sampling_strategy: rs
#   n_best_actions: 16  # Only for random sampling strategy
#   cem_steps: 10  # Only for CEM
#   regularization_weight: .0
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask:
#   - 1.0
#   - 0.9
#   - 0.8
#   - 0.7
#   - 0.6
#   - 0.5
#   - 0.4
#   - 0.1
#   - 0.1
#   - 1.0
#   - 0.9
#   - 0.8
#   - 0.7
#   - 0.6
#   - 0.5
#   - 0.4
#   - 0.1
#   - 0.1
#   - 10.0
#   - 10.0
#   - 10.0
#   - 0.1
#   - 0.1
#   - 0.1
#   - 0.1
#   knnK: 16
#   sim:
#     tau_sim: 0.005
#     tau_action: 0.25
#     interpolate_actions: false
#     joints_are_same_as_ctrl: false
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/franka_emika_panda/pandas_table.xml
#     camera: fixed_cam
# configs_path: configs/stable/grasp_configs.h5
