# RRT:
#   verbose: 3
#   max_nodes: 1000
#   min_cost: 0.05
#   horizon: 1
#   max_configs: -1
#   stepsize: [
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .05,  # waist
#     .75, .75, .75,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#     .05, .05, .05,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#   ]
#   path_diff_thresh: 0.05
#   target_min_dist: 100.
#   target_prob: .2
#   disable_node_max_strikes: 1  # Change to ratio: success/total
#   sample_uniform: false
#   warm_start: false
#   threading: true  # Depending on the hardware this may lead to faster computations.
#   start_idx: 8
#   end_idx: -1
#   bidirectional: false
#   cost_max_method: false
#   sample_count: 1000
#   sampling_strategy: rs
#   n_best_actions: 16  # Only for random sampling strategy
#   cem_steps: 5  # Only for CEM
#   regularization_weight: .0
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask: [
#     0., 0., 0., 1., 1., 1., 1.,
#     1., 1., 1.,  # hip
#     .75, .25, .25,  # knee, ankle, ankle
#     1., 1., 1.,  # hip
#     .5, .25, .25,  # knee, ankle, ankle
#     1.25, 1.25, 1.25,  # waist
#     .75, .75, .75,  # shoulder
#     .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
#     .75, .75, .75,  # shoulder
#     .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
#   ]
#   knnK: 16
#   sim:
#     tau_sim: 0.005
#     tau_action: 0.2
#     interpolate_actions: true
#     joints_are_same_as_ctrl: true
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/unitree_g1/g1_single.xml
#     camera: fixed_cam
# configs_path: configs/stable/g1.h5

# RRT:
#   verbose: 3
#   # max_nodes: 12000000
#   max_nodes: 7500
#   min_cost: 0.2
#   horizon: 1
#   max_configs: -1
#   stepsize:
#   - 0.3
#   - 0.3
#   - 0.4
#   - 0.5
#   - 0.7
#   - 0.6
#   - 1.0
#   - 125.0
#   - 0.3
#   - 0.3
#   - 0.4
#   - 0.5
#   - 0.7
#   - 0.6
#   - 1.0
#   - 125.0
#   path_diff_thresh: 0.1
#   target_min_dist: 100.
#   target_prob: .2
#   disable_node_max_strikes: 1
#   sample_uniform: false
#   warm_start: false
#   threading: true  # Depending on the hardware this may lead to faster computations.
#   start_idx: 1
#   end_idx: -1
#   bidirectional: false
#   cost_max_method: false
#   sample_count: 1000
#   sampling_strategy: rs
#   n_best_actions: 16  # Only for random sampling strategy
#   cem_steps: 10  # Only for CEM
#   regularization_weight: .0
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask:
#   - 1.0
#   - 0.9
#   - 0.8
#   - 0.7
#   - 0.6
#   - 0.5
#   - 0.4
#   - 0.1
#   - 0.1
#   - 1.0
#   - 0.9
#   - 0.8
#   - 0.7
#   - 0.6
#   - 0.5
#   - 0.4
#   - 0.1
#   - 0.1
#   - 10
#   - 10
#   - 10
#   - 0.1
#   - 0.1
#   - 0.1
#   - 0.1
#   knnK: 16
#   sim:
#     tau_sim: 0.001
#     tau_action: 0.5
#     interpolate_actions: true
#     joints_are_same_as_ctrl: false
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/franka_emika_panda/pandas_table.xml
#     camera: fixed_cam
# configs_path: configs/stable/grasp_configs.h5

# RRT:
#   verbose: 3
#   max_nodes: 600000
#   min_cost: 0.02
#   horizon: 1
#   max_configs: 100
#   stepsize: 0.1
#   path_diff_thresh: 0.05
#   target_min_dist: 10.
#   target_prob: .2
#   disable_node_max_strikes: 1
#   sample_uniform: false
#   warm_start: false
#   threading: true  # Depending on the hardware this may lead to faster computations.
#   start_idx: -1
#   end_idx: -1
#   bidirectional: false
#   cost_max_method: false
#   sample_count: 500
#   sampling_strategy: rs
#   n_best_actions: 16  # Only for random sampling strategy
#   cem_steps: 10  # Only for CEM
#   regularization_weight: .01
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask:
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - .25
#   - .25
#   - .25
#   - .25
#   knnK: 16
#   sim:
#     tau_sim: 0.005
#     tau_action: 0.2
#     interpolate_actions: true
#     joints_are_same_as_ctrl: true
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/twoFingersCube.xml
#     camera: fixed_cam
# configs_path: configs/stable/twoFingersCube.h5



# RRT:
#   verbose: 3
#   max_nodes: 10000
#   min_cost: 0.1
#   horizon: 1
#   max_configs: -1
#   stepsize:
#   - 0.15
#   - 0.15
#   - 0.2
#   - 0.25
#   - 0.35
#   - 0.3
#   - 0.5
#   - 125.0
#   path_diff_thresh: 0.05
#   target_min_dist: 1000.
#   target_prob: .0
#   disable_node_max_strikes: 1
#   sample_uniform: false
#   warm_start: false
#   threading: true  # Depending on the hardware this may lead to faster computations.
#   start_idx: 36
#   end_idx: 52
#   bidirectional: false
#   cost_max_method: false
#   sample_count: 500
#   sampling_strategy: rs
#   n_best_actions: 16  # Only for random sampling strategy
#   cem_steps: 10  # Only for CEM
#   regularization_weight: .0
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask: [
#     1.0, 0.9, 0.8, 0.7, 0.6, 0.4, 0.1, 0.05, 0.05,
#     10.0, 10.0, 10.0, 0.0, 0.0, 0.0, 0.0,
#     5.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0
#   ]
#   knnK: 16
#   sim:
#     tau_sim: 0.005
#     tau_action: 0.25
#     interpolate_actions: true
#     joints_are_same_as_ctrl: false
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/franka_emika_panda/panda_single.xml
#     camera: fixed_cam
# configs_path: configs/stable/pandaHook.h5

hydra:
  sweeper:
    params:
      RRT.n_best_actions: 1, 2, 4, 8, 16, 32, 64

RRT:
  verbose: 3
  max_nodes_per_tree: 2500
  min_cost: 0.05
  horizon: 1
  max_configs: 100
  stepsize: 0.05
  path_diff_thresh: 0.05
  target_min_dist: 10.
  target_prob: .2
  disable_node_max_strikes: -1
  sample_uniform_prob: 0
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  end_idx: -1
  bidirectional: false
  cost_method: se
  knnK: 16
  sample_count: 500
  sampling_strategy: rs
  n_best_actions: 16  # Only for random sampling strategy
  cem_steps: 10  # Only for CEM
  regularization_weight: .01
  output_dir: ${hydra:runtime.output_dir}
  q_mask:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 2
  - .25
  - .25
  - .25
  - .25

  sim:
    tau_sim: 0.005
    tau_action: 0.25
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/twoFingersCube.xml
    camera: fixed_cam
configs_path: configs/stable/twoFingersCube.h5
