RRT:
  verbose: 3
  max_nodes: 5000
  min_cost: 0.02
  horizon: 1
  max_configs: 100
  stepsize: 0.05
  path_diff_thresh: 0.05
  k_nearest_targets: -1
  target_prob: .1
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 17
  end_idx: -1
  bidirectional: false
  cost_max_method: false
  n_best_actions: 1  # Only for random sampling strategy
  sample_count: 500
  sampling_strategy: rs
  cem_steps: 3
  regularization_weight: .0
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.0, 4.0, 4.0,
    0.1, 0.1, 0.1, 0.1
  ]
  knnK: 16
  sim:
    tau_sim: 0.005
    tau_action: 0.25
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/twoFingersCube.xml
    camera: fixed_cam
configs_path: configs/stable/twoFingersCube.h5
