# RRT:
#   verbose: 3
#   max_nodes: 10000
#   min_cost: 0.06
#   max_configs: 128
#   stepsize: [
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .075,  # hip
#     .1, .1, .1,  # knee, ankle, ankle
#     .075, .05, .05,  # waist
#     .75, .75, .75,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#     .05, .05, .05,  # shoulder
#     .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
#   ]
#   path_diff_thresh: 0.05
#   target_min_dist: 100.
#   target_prob: .15
#   sample_uniform: false
#   start_idx: 8
#   end_idx: -1
#   cost_max_method: false
#   output_dir: ${hydra:runtime.output_dir}
#   q_mask: [
#     2., 2., 2., .25, .25, .25, .25,
#     .5, .5, .5,  # hip
#     .4, .125, .125,  # knee, ankle, ankle
#     .5, .5, .5,  # hip
#     .25, .125, .125,  # knee, ankle, ankle
#     .7, .7, .7,  # waist
#     .4, .4, .4,  # shoulder
#     .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
#     .4, .4, .4,  # shoulder
#     .25, .125, .125, .125,  # elbow, wrist, wrist, wrist
#   ]
#   knnK: 32
#   sim:
#     tau_sim: 0.001
#     tau_action: 0.1
#     interpolate_actions: false
#     joints_are_same_as_ctrl: false
#     use_spline_ref: false
#     mujoco_xml: configs/mujoco_/g1/scene.xml
#     camera: fixed_cam
# configs_path: configs/stable/g1.h5

# # hydra:
# #   sweeper:
# #     params:
# #       RRT.horizon: 1, 2, 4
# #       RRT.max_configs: 128, -1
# #       RRT.sim.use_spline_ref: true, false
# #       RRT.regularization_weight: .0, .1
# #       RRT.sampling_strategy: cem, rs


RRT:
  verbose: 3
  max_nodes: 3500
  min_cost: 0.1
  horizon: 1
  max_configs: -1
  stepsize: [
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .075,  # hip
    .1, .1, .1,  # knee, ankle, ankle
    .075, .05, .05,  # waist
    .75, .75, .75,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
    .05, .05, .05,  # shoulder
    .075, .1, .1, .1,  # elbow, wrist, wrist, wrist
  ]
  path_diff_thresh: 0.05
  target_min_dist: 1.
  target_prob: .1
  disable_node_max_strikes: 1
  sample_uniform: false
  warm_start: false
  threading: true  # Depending on the hardware this may lead to faster computations.
  start_idx: 8
  end_idx: -1
  bidirectional: false
  cost_max_method: true
  sample_count: 500
  sampling_strategy: cem
  n_best_actions: 1  # Only for random sampling strategy
  cem_steps: 10  # Only for CEM
  regularization_weight: .0
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [
    1., 1., 1., .75, .75, .75, .75,
    1., 1., 1.,  # hip
    .75, .25, .25,  # knee, ankle, ankle
    1., 1., 1.,  # hip
    .5, .25, .25,  # knee, ankle, ankle
    1.25, 1.25, 1.25,  # waist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
    .75, .75, .75,  # shoulder
    .5, .25, .25, .25,  # elbow, wrist, wrist, wrist
  ]
  knnK: 4
  sim:
    tau_sim: 0.005
    tau_action: 0.2
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    use_spline_ref: false
    mujoco_xml: configs/mujoco_/unitree_g1/g1_single.xml
    camera: fixed_cam
configs_path: configs/stable/g1.h5
