RRT:
  max_nodes: 500000
  min_cost: 0.02
  stepsize: 0.1
  verbose: 1
  target_prob: 0.2
  sample_uniform: false
  warm_start: false
  threading: true
  start_idx: -1
  end_idx: -1
  bidirectional: false
  cost_max_method: false
  sample_count: 100
  sampling_strategy: rs
  output_dir: ${hydra:runtime.output_dir}
  q_mask: [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
  knnK: 16
  sim:
    tau_sim: 0.001
    tau_action: 0.5
    interpolate_actions: true
    joints_are_same_as_ctrl: true
    mujoco_xml: configs/fingerRamp.xml
    camera: wrist_cam
configs_path: configs/fingerRamp_onRamp.h5
